"""Alembic environment.

Migrations are written as SQL (op.execute), not autogenerated from ORM models: the
parts of this schema that matter most (RLS policies, the HNSW index, the delete
trigger) are things autogenerate cannot express anyway.
"""

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

config = context.config
if config.config_file_name and not config.attributes.get("skip_logging"):
    fileConfig(config.config_file_name, disable_existing_loggers=False)


def database_url() -> str:
    url = config.get_main_option("sqlalchemy.url") or os.environ["DATABASE_URL"]
    # the app uses psycopg 3 directly; tell SQLAlchemy to use the same driver
    return url.replace("postgresql://", "postgresql+psycopg://", 1)


def run_migrations_offline() -> None:
    context.configure(url=database_url(), literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(database_url(), poolclass=pool.NullPool)
    with engine.connect() as connection:
        context.configure(connection=connection, transaction_per_migration=True)
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
